Checks to ReportViewer for export in file if that file already exists
QualitySolution/My-FyiReporting pull request #10
Opened 2021-09-21 14:05 UTC by DobriyMisha

Добавлена кастомная проверка на существование файла с таким именем в директории при сохранении выгрузки
DoOverwrite не работала в данном случае, так как невозможно было присвоить имени файла необходимое расширение ДО выполнения процедуры проверки DoOverwriteConfirmation, следовательно процедура не замечает существования дубликата файла так как текущий сохраняемый файл не имеет расширения в своем имени
Также по задаче необходимо было изменить локализацию кнопок и заголовка, сделано это через ресурсы RdlEngine (чтобы не иметь кириллицы в коде проекта).
Для доступа к ресурсам из другого проекта пришлось модификаторы доступа ресурсов сделать public.

2021-09-23 13:18 UTC, Gankov commented
Давай это исправление тоже в основной репозиторий зальем.
Только ToRussian убери из названия ресурса.

2021-09-23 13:19 UTC, Gankov commented
Сделай пожалуйста сюда https://github.com/majorsilence/My-FyiReporting пул реквест. Я его приму.

2021-09-23 16:10 UTC, DobriyMisha commented
> Давай это исправление тоже в основной репозиторий зальем.
> Только ToRussian убери из названия ресурса.

Сделаем

2021-09-23 20:23 UTC, DobriyMisha commented
> Сделай пожалуйста сюда https://github.com/majorsilence/My-FyiReporting пул реквест. Я его приму.

Подожди, там же нет ветки QSbuild. В мастер лить? Если в мастер, то надо значит все мне коммиты последние стягивать с QSbuild, если там новые появились за то время пока мой ПР висит, правильно?

2021-09-24 08:06 UTC, Gankov commented
> > Сделай пожалуйста сюда https://github.com/majorsilence/My-FyiReporting пул реквест. Я его приму.
> 
> Подожди, там же нет ветки QSbuild. В мастер лить? Если в мастер, то надо значит все мне коммиты последние стягивать с QSbuild, если там новые появились за то время пока мой ПР висит, правильно?

Лучше чери пиком комиты перетащи.

2021-09-24 13:33 UTC, DobriyMisha commented
> > > Сделай пожалуйста сюда https://github.com/majorsilence/My-FyiReporting пул реквест. Я его приму.
> > 
> > 
> > Подожди, там же нет ветки QSbuild. В мастер лить? Если в мастер, то надо значит все мне коммиты последние стягивать с QSbuild, если там новые появились за то время пока мой ПР висит, правильно?
> 
> Лучше чери пиком комиты перетащи.

Все сделано, ПР лежит

2021-09-27 08:29 UTC, Enzogord requested changes

2021-09-27 08:29 UTC, Enzogord commented on RdlEngine/Resources/Strings.resx
> +  <data name="ButtonSave_Text_ToRussian" xml:space="preserve">
Имя ButtonSave_Text_ToRussian, а значение на английском. Возможно имя ресурса не правильное.

2021-09-27 08:45 UTC, DobriyMisha commented on RdlEngine/Resources/Strings.resx
> +  <data name="ButtonSave_Text_ToRussian" xml:space="preserve">
Поправил

2022-10-05 10:48 UTC, Gankov commented
Было добавлено в апстрим.

2022-10-05 10:48 UTC, closed without merging